version: '3.4'

services:
  couchbase:
    image: couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password

  pixmicroservice:
    image: pixmicroservice
    build:
      context: .
      dockerfile: Dockerfile.txt
    ports:
      - "5217:5217"
      - "8080:8080"
    depends_on:
      - couchbase
    environment:
      - Couchbase__ConnectionString=couchbase://couchbase
      - Couchbase__Username=Administrator
      - Couchbase__Password=password
      - Couchbase__Bucket=PixBucket
